name: Build Web App (Self-Hosted)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: self-hosted

    defaults:
      run:
        shell: cmd
        working-directory: ./web # Chạy các lệnh NPM bên trong thư mục web

    steps:
      - name: Checkout React App
        uses: actions/checkout@v4
        with:
          repository: 'uitbestteam/checkpoint-app-reactjs'
          ref: 'main'
          path: web

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Sử dụng bản LTS ổn định

      - name: Install dependencies
        run: npm.cmd install

      - name: Build project
        run: npm.cmd run build
