name: Build Web App (Self-Hosted)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: self-hosted

    defaults:
      run:
        shell: cmd # Giữ nguyên cmd để không lo bị chặn bởi PowerShell Execution Policy

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Chạy bản Node 24 mới nhất

      - name: Install dependencies
        run: npm.cmd install # Thêm đuôi .cmd để Windows CMD gọi trực tiếp không qua trung gian

      - name: Build project
        run: npm.cmd run build
